swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      summary: Obtenir toutes les transactions du mois en cours
      operationId: getTransactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        200:
          description: Liste des transactions du mois en cours
        400:
          description: Invalid Fields
        500:
          description: Internal Server Error
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
  /transactions/{transactionId}:
    get:
      summary: Obtenir les détails d'une transaction spécifique
      operationId: getTransactionDetails
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: Détails d'une transaction spécifique
        400:
          description: Invalid Fields
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/TransactionDetails'
    put:
      summary: Mettre à jour une transaction
      operationId: updateTransaction
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/UpdateTransaction'
      produces:
        - application/json
      responses:
        200:
          description: Transaction mise à jour
        400:
          description: Invalid Fields
        500:
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
      accountId:
        type: string
  TransactionDetails:
    type: object
    allOf:
      - $ref: '#/definitions/Transaction'
      - type: object
        properties:
          category:
            type: string
          notes:
            type: string
  UpdateTransaction:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string